package org.toxsoft.uskat.core.backend.api;

/**
 * Messages generated by {@link IBaCommands} addon to the frontend.
 *
 * @author hazard157
 */
public interface IBaCommandsMessages
    extends IBackendAddon {

  // ------------------------------------------------------------------------------------
  // Message: ???

  /**
   * The message ID.
   */
  // String MSGID_CLOB_CHANGE = "ClobChange"; //$NON-NLS-1$

}
